str = input()
for i in str:
    n = int(i)
    if n == 0:
        print("0000")
        print("0  0")
        print("0  0")
        print("0  0")
        print("0000")
    elif n == 1:
        print("   1")
        print("   1")
        print("   1")
        print("   1")
        print("   1")
    elif n == 2:
        print("2222")
        print("   2")
        print("2222")
        print("2")
        print("2222")
    elif n == 3:
        print("3333")
        print("   3")
        print("3333")
        print("   3")
        print("3333")
    elif n == 4:
        print("4  4")
        print("4  4")
        print("4444")
        print("   4")
        print("   4")
    elif n == 5:
        print("5555")
        print("5")
        print("5555")
        print("   5")
        print("5555")
    elif n == 6:
        print("6666")
        print("6")
        print("6666")
        print("6  6")
        print("6666")
    elif n == 7:
        print("7777")
        print("   7")
        print("   7")
        print("   7")
        print("   7")
    elif n == 8:
        print("8888")
        print("8  8")
        print("8888")
        print("8  8")
        print("8888")
    elif n == 9:
        print("9999")
        print("9  9")
        print("9999")
        print("   9")
        print("   9")
    print()